import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./_components/HeaderComponent";
import { ColorModeScript } from "@chakra-ui/react";
import Chakra from "./_components/Chakra";
import theme from "@/styles/theme";
import { useServerCookies } from "@/utils/useServerCookies";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = await useServerCookies();
  return (
    <html lang="en">
      <head>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      </head>
      <body className={inter.className}>
        <Chakra>
          <HeaderComponent sheetURL={cookies.sheetURL} />
          {children}
        </Chakra>
      </body>
    </html>
  );
}
